version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_service
    ports:
      - "8000:8000"
    volumes:
      - ./inference:/app/inference
      - ./model:/app/model
    networks:
      - webnet

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: telegram_bot
    volumes:
      - ./bot:/bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    depends_on:
      - fastapi
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
